project_id = "cbypedcyszozqezowbbo"

[functions]

[functions.summarize-gratitude]
verify_jwt = true

[functions.generate-wrapped]
verify_jwt = true

[functions.daily-reminder]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[realtime]
enabled = true

[realtime.tables.profiles]
enabled = true

[realtime.tables.claimed_activities]
enabled = true

[realtime.tables.likes]
enabled = true

[realtime.tables.comments]
enabled = true

[realtime.tables.comment_likes]
enabled = true
