

[functions]

[realtime]
enabled = true

[realtime.tables.profiles]
enabled = true

[realtime.tables.claimed_activities]
enabled = true

[realtime.tables.likes]
enabled = true

[realtime.tables.comments]
enabled = true

[realtime.tables.comment_likes]
enabled = true

